
services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./pg_db/postgres-data:/var/lib/postgresql/data

  bot:
    depends_on: 
      - db
    build: .
    container_name: outokumpu_bot
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_HOST=db
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}


